name = "PowerMonitor"
uuid = "9e7e054f-393b-40f5-81e8-49c2b2540836"
authors = ["Ian <i.r.butterworth@gmail.com>"]
version = "0.1.0"

[deps]
battery_cli_jll = "dd074c01-bd9e-510d-b91d-361c690844c9"

[compat]
battery_cli_jll = "0.10, 0.11"
julia = "1.9"
